const {VertexAI } = require('@google-cloud/vertexai');

// Initialize Vertex with your Cloud project and location
const vertex_ai = new VertexAI({project: 'shothikai-gcp', location: 'us-central1'});
const model = 'gemini-1.5-pro-002'
const generationConfig = {
    'maxOutputTokens': 8192,
    'temperature': 1,
    'topP': 0.89,
  }

// meeting model 
// const meetingModel = vertex_ai.preview.getGenerativeModel({
//   model,
//   generationConfig,
//   safetySettings: [],
//   systemInstruction: {
//     parts: [
//       {
//         text: `Generate detailed meeting minutes in HTML format based on the transcribed data in its original language. The minutes should reflect the following structure:

//         Agenda Items: Include all agenda topics discussed during the meeting.

//         Discussions and Decisions: For each agenda item, summarize the key discussions and decisions made.

//         Action Items: Specify tasks, assign responsibilities to individuals, and mention deadlines.

//         Reports/Updates: Summarize any reports or presentations shared during the meeting.

//         Follow-up Items: List tasks carried over from the previous meeting that require attention.

//         Start Time and End Time: Mention when the meeting started and adjourned.

//         Ensure that the entire output, including agenda items, discussions, decisions, and actions, is presented in the language of the transcribed data.

//         Display the meeting minutes in an HTML table format at the end.

//         Use the <strong>, <ins>, <ul>, <li>, <table>, and <tr> tags where needed. Each header and sub header should be enclosed in <strong> tags. The date should be underlined using the <u> tag.
        
//         Generated By: At the end, add "This meeting is generated by SHOTHIK AI".
//         `,
//       },
//     ],
//   },
// });


const detectLanguageModel = vertex_ai.preview.getGenerativeModel({
  model,
  generationConfig,
  safetySettings: [],
  systemInstruction: {
    parts: [
      {
        text: `Detect the language first and then select the format is given below.
         `,
      },
    ],
  },
});


const summaryModel = vertex_ai.preview.getGenerativeModel({
  model,
  generationConfig,
  safetySettings: [],
  systemInstruction: {
    parts: [
      {
        text: `Generate meeting minutes based on the following input data. The output should closely resemble the format and style of the sample meeting minutes provided. The minutes should include:

            Heading: [Meeting Title] - [Date] at [Time] in [Location] (Replace with actual data)
            Attendees:  List of attendees (if provided). 
            Summary: A concise summary of the key discussions and decisions made during the meeting.
            Action Items: A table summarizing each discussed item, including the topic, discussion points, decisions made, and responsible parties. The table should be structured similarly to the sample.
            Closing: A concluding statement indicating the end of the meeting.

            Exclude non-essential details and additional commentary.
         `,
      },
    ],
  },
});

const meetingModel = vertex_ai.preview.getGenerativeModel({
  model,
  generationConfig,
  safetySettings: [],
  systemInstruction: {
    parts: [
      {
        text: `Generate the content in HTML format, using appropriate HTML tags to ensure clear and organized presentation. For headings, use <h1>, <h2>, etc., as appropriate. Use <p> for paragraphs, <ul> and <li> for lists, and <table>, <tr>, <th>, and <td> for tabular data, ensuring each table includes a border for clarity (e.g., <table border="1">). Use <br> for line breaks as needed. Ensure all elements are properly nested, with no extra spaces outside the tags, to ensure the content displays well in an HTML environment.
        `,
      },
    ],
  },
});


async function createMeetingModel(systemInstruction) {
  return vertex_ai.preview.getGenerativeModel({
    model: 'gemini-1.5-pro-002',
    generationConfig: {
      'maxOutputTokens': 8192,
      'temperature': 1,
      'topP': 0.89,
    },
    safetySettings: [],
    systemInstruction: {
      parts: [
        {
          text: systemInstruction,
        },
      ],
    },
  });
}

module.exports = {
  meetingModel,
  summaryModel,
  detectLanguageModel,
  createMeetingModel,
}


// {
//   text: `you are pro meeting minutes generator with 30 years of experience now generate meeting minutes in bn language 

//     1. Title: Include the title of the meeting.
//     2. Date: Include the date on which the meeting took place.
//     3. Participants: Specify the main participants in the meeting, such as the president, speakers, and important group members.
//     4. Agenda Discussion: Highlight the key points of the agenda, such as the approval of the agenda, proposed resolutions, or issues addressed and for each point indicate the key decisions taken during the meeting, including voting results and approved resolutions. Always include each speaker what they have said in short.
//     5. Results and Future Actions: Specify future planned actions or commitments made during the meeting to address the discussed topics.
//     6. Conclusions: Offer a concise conclusion that summarizes the overall flow of the meeting and highlights any important matters that require further actions or future discussions.
//     7. Next Meeting: If applicable, indicate the date and time of the next meeting to keep participants informed.
//     8. Any Open Issues: Report any unresolved issues or problems that require further discussions or actions.
    
//     Give a brief description of what each speaker has said. Give me in html formate where every point will be strong tag.
//   `,
// },

// parts: [
//       {
//         text: `Generate the HTML code for the meeting minutes in Bengali language upon the user providing the content. Returning a code snippet without further explanations.

//         1.Title: Include the title of the meeting in HTML format.
//         2. Date: Include the date on which the meeting took place, underlined in HTML format .
//         3. Participants: Specify the main participants in the meeting, such as the president, speakers, and important group members in       HTML format. 
//         4.Agenda Discussion: Write the key points of the agenda, such as the approval of the agenda, proposed resolutions, or issues addressed.
//         5. For each point, indicate the key decisions taken during the meeting, including voting results and approved resolutions. b Speaker Contributions:
//         6. Always include a brief summary of what each speaker has said in HTML format. 
//         7. Results and Future Actions: Specify future planned actions or commitments made during the meeting to address the discussed topics in HTML format. 
//         8.Conclusions: Offer a concise conclusion that summarizes the overall flow of the meeting and highlights any important matters that require further actions or future discussions in HTML format. 
//         9. Next Meeting: If applicable, indicate the date and time of the next meeting; if not mentioned, simply state "not applicable" to keep participants informed in HTML format.
//         10. Any Open Issues: Report any unresolved issues or problems that require further discussions or actions in HTML format. Summary Table: 
//         11.Display the meeting minutes in an HTML table format at the end.
//         12. Brief Summary: Add a brief summary under the table. 
//         13.Formatting: Use the <strong>, <ins>, <ul>, <li>, <table>, and <tr> tags where needed. Each header and sub header should be enclosed in <strong> tags. The date should be underlined using the <u> tag.
//         14. Generated By: At the end, add "This meeting is generated by SHOTHIK AI".
//         `,
//       },
//     ],

// Generate a formal meeting minutes document in [Language Code or Name] for a meeting of [Organization Name] held on [Date] at [Time] in [Location]. The purpose of the meeting was [Meeting Purpose].
//             Attendees: [List Attendees and their Roles/Titles]
//             Meeting Summary: Provide a detailed summary of the discussion, including key decisions made and any agreements reached. Use headings and subheadings to organize the information clearly. Use [Language Name] terminology appropriately.
//             Action Items: Create a table with the following columns: Task, Assignee, Due Date, Status (e.g., To Do, In Progress, Completed).
//             Attachments: [List any attached documents or materials]
//             Next Meeting: Date and time of the next meeting (if applicable)