const mongoose = require("mongoose");
const jwt = require("jsonwebtoken");
const { OAuth2Client } = require("google-auth-library");
const msal = require("@azure/msal-node");
const {
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  GOOGLE_REDIRECT_URI,
} = require("../../config/constant");

// MS Credentials
const MS_CLIENT_ID = "MS_CLIENT_ID";
const MS_CLIENT_SECRET = "MS_CLIENT_SECRET";
const MS_TENANT_ID = "MS_TENANT_ID";

const userSchema = new mongoose.Schema(
  {
    name: {
      type: String,
      maxLength: [25, "Name cannot exceed 50 characters"],
      minLength: [3, "Name should have more than 3 characters"],
    },
    email: {
      type: String,
      required: [true, "Please Enter your Email"],
      unique: true,
      validate: {
        validator: function (email) {
          const domain = email.split("@")[1];
          return !temporaryEmailDomains.includes(domain);
        },
        message: "Temporary email addresses are not allowed",
      },
    },
    password: {
      type: String,
    },
    auth_type: {
      type: String,
      enum: ["google", "manual"],
      required: true,
    },
    package: {
      type: String,
      required: true,
      enum: ["free", "value_plan", "pro_plan", "unlimited"],
      default: "free",
    },
    is_verified: {
      type: Boolean,
      default: false,
    },
    // external use
    address: {
      type: String,
      maxLength: [250, "Address cannot exceed 30 characters"],
      required: false,
    },
    country: {
      type: String,
      maxLength: [50, "Country cannot exceed 30 characters"],
      required: false,
    },
    state: {
      type: String,
      maxLength: [50, "State cannot exceed 30 characters"],
      required: false,
    },
    city: {
      type: String,
      maxLength: [50, "City cannot exceed 30 characters"],
      required: false,
    },
    zipCode: {
      type: String,
      required: false,
    },
    image: {
      type: String,
      default: "",
    },
    status: {
      type: String,
      enum: ["active", "disabled"],
      default: "active",
    },
    role: {
      type: String,
      enum: ["user", "admin"],
      default: "user",
    },
    googleAccessToken: String,
    googleRefreshToken: String,
    googleTokenExpiryDate: Date,
    msAccessToken: String,
    msRefreshToken: String,
    msTokenExpiryDate: Date,
  },
  {
    timestamps: true,
  }
);

const User = mongoose.model("User", userSchema);

// generateAuthToken

const generateAuthToken = function (user) {
  const token = jwt.sign(
    {
      _id: user._id,
      sub: user._id,
      email: user.email,
      package: user.package,
      is_verified: user.is_verified,
      role: user.role,
    },
    process.env.JWT_SECRET ?? "secret"
  );
  return token;
};

// Save Google tokens
async function authorize(userId, callback) {
  try {
    const user = await User.findById(userId);
    if (!user) throw new Error("User not found");

    const oAuth2Client = new OAuth2Client(
      GOOGLE_CLIENT_ID,
      GOOGLE_CLIENT_SECRET,
      GOOGLE_REDIRECT_URI
    );

    const now = new Date();
    if (user.googleTokenExpiryDate <= now) {
      const newAccessToken = await refreshGoogleAccessToken(user);
      oAuth2Client.setCredentials({ access_token: newAccessToken });
    } else {
      oAuth2Client.setCredentials({ access_token: user.googleAccessToken });
    }

    callback(oAuth2Client);
  } catch (error) {
    console.error("Authorization error:", error);
    throw error;
  }
}

const saveGoogleTokens = async (userId, tokens) => {
  await User.findByIdAndUpdate(userId, {
    googleAccessToken: tokens.access_token,
    googleRefreshToken: tokens.refresh_token,
    googleTokenExpiryDate: new Date(
      tokens.expiry_date || Date.now() + tokens.expires_in * 1000
    ),
  });
};

const refreshGoogleAccessToken = async (user) => {
  const oAuth2Client = new OAuth2Client(
    GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET,
    GOOGLE_REDIRECT_URI
  );
  oAuth2Client.setCredentials({ refresh_token: user.googleRefreshToken });

  try {
    const { credentials } = await oAuth2Client.refreshAccessToken();
    await saveGoogleTokens(user._id, credentials);
    return credentials.access_token;
  } catch (error) {
    console.error("Error refreshing Google access token", error);
    throw error;
  }
};

const getGoogleOAuthClient = async (user) => {
  if (new Date() >= new Date(user.googleTokenExpiryDate)) {
    const newAccessToken = await refreshGoogleAccessToken(user);
    return new OAuth2Client(
      GOOGLE_CLIENT_ID,
      GOOGLE_CLIENT_SECRET,
      GOOGLE_REDIRECT_URI,
      { access_token: newAccessToken }
    );
  }
  return new OAuth2Client(
    GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET,
    GOOGLE_REDIRECT_URI,
    { access_token: user.googleAccessToken }
  );
};

const saveMsTokens = async (userId, tokens) => {
  await User.findByIdAndUpdate(userId, {
    msAccessToken: tokens.accessToken,
    msRefreshToken: tokens.refreshToken,
    msTokenExpiryDate: new Date(tokens.expiresOn),
  });
};

const refreshMsAccessToken = async (user) => {
  const cca = new msal.ConfidentialClientApplication({
    auth: {
      clientId: MS_CLIENT_ID,
      authority: `https://login.microsoftonline.com/${MS_TENANT_ID}`,
      clientSecret: MS_CLIENT_SECRET,
    },
  });

  try {
    const response = await cca.acquireTokenByRefreshToken({
      refreshToken: user.msRefreshToken,
      scopes: ["https://graph.microsoft.com/.default"],
    });
    await saveMsTokens(user._id, response);
    return response.accessToken;
  } catch (error) {
    console.error("Error refreshing Microsoft access token", error);
    throw error;
  }
};

const getMsAuthToken = async (user) => {
  if (new Date().getTime() >= new Date(user.msTokenExpiryDate).getTime()) {
    return await refreshMsAccessToken(user);
  }
  return user.msAccessToken;
};

module.exports = {
  User,
  generateAuthToken,
  getGoogleOAuthClient,
  refreshGoogleAccessToken,
  saveGoogleTokens,
  saveMsTokens,
  refreshMsAccessToken,
  getMsAuthToken,
};

const temporaryEmailDomains = [
  "0-mail.com",
  "027168.com",
  "0815.ru",
  "10mail.com",
  "10minutemail.com",
  "123-m.com",
  "1mail.x24hr.com",
  "2prong.com",
  "30minutemail.com",
  "33mail.com",
  "4warding.com",
  "5mail.cf",
  "60minutemail.com",
  "666post.com",
  "6ip.us",
  "6mail.cf",
  "7mail.ga",
  "7tags.com",
  "9ox.net",
  "a-bc.net",
  "a45.in",
  "abusemail.de",
  "abyssmail.com",
  "add3000.pp.ua",
  "advantimo.com",
  "afrobacon.com",
  "ajaxapp.net",
  "amail.com",
  "amail4.me",
  "ama-trade.de",
  "anonbox.net",
  "anonmails.de",
  "anonymbox.com",
  "antispam.de",
  "antispammail.de",
  "armyspy.com",
  "artman-conception.com",
  "asdasd.nl",
  "azmeil.tk",
  "baxomale.ht.cx",
  "beefmilk.com",
  "bigstring.com",
  "binkmail.com",
  "bio-muesli.net",
  "bobmail.info",
  "bodhi.lawlita.com",
  "bootybay.de",
  "boun.cr",
  "bouncr.com",
  "boxformail.in",
  "brefmail.com",
  "brennendesreich.de",
  "bsnow.net",
  "bugmenot.com",
  "bund.us",
  "burstmail.info",
  "buymoreplays.com",
  "byom.de",
  "c2.hu",
  "card.zp.ua",
  "casualdx.com",
  "cek.pm",
  "centermail.com",
  "chammy.info",
  "childsavetrust.org",
  "chogmail.com",
  "choicemail1.com",
  "clixser.com",
  "cmail.net",
  "cmail.org",
  "coldemail.info",
  "consumerriot.com",
  "cool.fr.nf",
  "correo.blogos.net",
  "cosmorph.com",
  "courriel.fr.nf",
  "courrieltemporaire.com",
  "crapmail.org",
  "cubiclink.com",
  "curryworld.de",
  "cust.in",
  "cuvox.de",
  "d3p.dk",
  "dacoolest.com",
  "dandikmail.com",
  "dayrep.com",
  "dcemail.com",
  "deadaddress.com",
  "deadspam.com",
  "delikkt.de",
  "despam.it",
  "despammed.com",
  "devnullmail.com",
  "dfgh.net",
  "digitalsanctuary.com",
  "dingbone.com",
  "discard.cf",
  "discard.email",
  "discard.ga",
  "discard.gq",
  "discard.ml",
  "discard.tk",
  "discardmail.com",
  "discardmail.de",
  "dispostable.com",
  "divismail.ru",
  "dm.w3internet.co.uk",
  "dnset.com",
  "dodgeit.com",
  "dodgit.com",
  "dodgit.org",
  "dodsi.com",
  "doiea.com",
  "domozmail.com",
  "donemail.ru",
  "dontmail.net",
  "dontreg.com",
  "dontsendmespam.de",
  "drdrb.com",
  "dump-email.info",
  "dumpandjunk.com",
  "dumpmail.de",
  "dumpyemail.com",
  "e-mail.com",
  "e-mail.org",
  "e4ward.com",
  "easytrashmail.com",
  "einmalmail.de",
  "einrot.com",
  "email.cbes.net",
  "email60.com",
  "emaildienst.de",
  "emailgo.de",
  "emailias.com",
  "emailigo.de",
  "emailinfive.com",
  "emaillime.com",
  "emailsensei.com",
  "emailtemporanea.com",
  "emailtemporanea.net",
  "emailtemporar.ro",
  "emailtemporario.com.br",
  "emailthe.net",
  "emailtmp.com",
  "emailto.de",
  "emailwarden.com",
  "emailx.at.hm",
  "emailxfer.com",
  "emeil.in",
  "emil.com",
  "emkei.cz",
  "emz.net",
  "ero-tube.org",
  "etranquil.com",
  "etranquil.net",
  "etranquil.org",
  "evopo.com",
  "explodemail.com",
  "express.net.ua",
  "extremail.ru",
  "eyepaste.com",
  "facebook-email.cf",
  "facebookmail.gq",
  "fake-email.pp.ua",
  "fakeinbox.com",
  "fakeinformation.com",
  "fakeinbox.cf",
  "falseaddress.com",
  "fammix.com",
  "fansworldwide.de",
  "fantasymail.de",
  "farrse.co.uk",
  "fastacura.com",
  "fastchevy.com",
  "fastchrysler.com",
  "fastkawasaki.com",
  "fastmazda.com",
  "fastmitsubishi.com",
  "fastnissan.com",
  "fastsubaru.com",
  "fastsuzuki.com",
  "fasttoyota.com",
  "fastyamaha.com",
  "fightallspam.com",
  "figjs.com",
  "filzmail.com",
  "fixmail.tk",
  "fizmail.com",
  "fleckens.hu",
  "flurred.com",
  "flyspam.com",
  "footard.com",
  "forgetmail.com",
  "fornow.eu",
  "fr33mail.info",
  "frapmail.com",
  "friendlymail.co.uk",
  "front14.org",
  "fuckingduh.com",
  "fudgerub.com",
  "fux0ringduh.com",
  "fyii.de",
  "garbagemail.org",
  "gehensiemirnichtaufdensack.de",
  "get1mail.com",
  "get2mail.fr",
  "getairmail.cf",
  "getairmail.com",
  "getairmail.ga",
  "getairmail.gq",
  "getairmail.ml",
  "getmails.eu",
  "getonemail.com",
  "ghosttexter.de",
  "girlsundertheinfluence.com",
  "gishpuppy.com",
  "glubex.com",
  "gmial.com",
  "gmx.com",
  "gmx.net",
  "goemailgo.com",
  "gotmail.com",
  "gotmail.net",
  "gotmail.org",
  "gotti.otherinbox.com",
  "gowikibooks.com",
  "gowikicampus.com",
  "gowikicars.com",
  "gowikifilms.com",
  "gowikigames.com",
  "gowikimusic.com",
  "gowikinetwork.com",
  "gowikitravel.com",
  "gowikitv.com",
  "grandmamail.com",
  "grr.la",
  "gsrv.co.uk",
  "guerillamail.biz",
  "guerillamail.com",
  "guerrillamail.biz",
  "guerrillamail.com",
  "guerrillamail.de",
  "guerrillamail.info",
  "guerrillamail.net",
  "guerrillamail.org",
  "guerrillamailblock.com",
  "gustr.com",
  "harakirimail.com",
  "hat-geld.de",
  "hatespam.org",
  "hellodream.mobi",
  "herp.in",
  "hidemail.de",
  "hidzz.com",
  "hmamail.com",
  "hochsitze.com",
  "hopemail.biz",
  "hotpop.com",
  "hulapla.de",
  "ieatspam.eu",
  "ieatspam.info",
  "ieh-mail.de",
  "ihateyoualot.info",
  "iheartspam.org",
  "ikbenspamvrij.nl",
  "imails.info",
  "inbax.tk",
  "inbox.si",
  "inboxalias.com",
  "inboxclean.com",
  "inboxclean.org",
  "inboxproxy.com",
  "incognitomail.org",
  "infocom.zp.ua",
  "instant-mail.de",
  "ip6.li",
  "ipoo.org",
  "irish2me.com",
  "iwi.net",
  "jetable.com",
  "jetable.fr.nf",
  "jetable.net",
  "jetable.org",
  "jnxjn.com",
  "jourrapide.com",
  "junk1e.com",
  "junkmail.com",
  "junkmail.ga",
  "junkmail.gq",
  "justemail.ml",
  "kaspop.com",
  "kcrw.de",
  "keepmymail.com",
  "killmail.com",
  "killmail.net",
  "kir.ch.tc",
  "klassmaster.com",
  "klassmaster.net",
  "klzlk.com",
  "koszmail.pl",
  "kurzepost.de",
  "l33r.eu",
  "lackmail.net",
  "lags.us",
  "lawlita.com",
  "letthemeatspam.com",
  "lhsdv.com",
  "lifebyfood.com",
  "link2mail.net",
  "litedrop.com",
  "loadby.us",
  "login-email.cf",
  "login-email.ga",
  "login-email.ml",
  "login-email.tk",
  "lol.ovpn.to",
  "lolfreak.net",
  "lookugly.com",
  "lopl.co.cc",
  "lortemail.dk",
  "lr78.com",
  "lroid.com",
  "luisgiisjsk.tk",
  "lukop.dk",
  "m21.cc",
  "m4ilweb.info",
  "mail-easy.fr",
  "mail-filter.com",
  "mail-temporaire.fr",
  "mail.by",
  "mail.mezimages.net",
  "mail.zp.ua",
  "mail1a.de",
  "mail21.cc",
  "mail2rss.org",
  "mail333.com",
  "mail4trash.com",
  "mailbidon.com",
  "mailbiz.biz",
  "mailblocks.com",
  "mailbucket.org",
  "mailcat.biz",
  "mailcatch.com",
  "mailde.de",
  "mailde.info",
  "maildrop.cc",
  "maileater.com",
  "mailed.in",
  "mailexpire.com",
  "mailfa.tk",
  "mailforspam.com",
  "mailfreeonline.com",
  "mailguard.me",
  "mailin8r.com",
  "mailinater.com",
  "mailinator.com",
  "mailinator.net",
  "mailinator.org",
  "mailinator2.com",
  "mailincubator.com",
  "mailismagic.com",
  "mailme.lv",
  "mailme24.com",
  "mailmetrash.com",
  "mailmoat.com",
  "mailnator.com",
  "mailnesia.com",
  "mailnull.com",
  "mailpick.biz",
  "mailrock.biz",
  "mailscrap.com",
  "mailseal.de",
  "mailshell.com",
  "mailsiphon.com",
  "mailslapping.com",
  "mailslite.com",
  "mailtemp.info",
  "mailtothis.com",
  "mailtrash.net",
  "mailtv.net",
  "mailtv.tv",
  "mailzilla.com",
  "mailzilla.org",
  "makemetheking.com",
  "manybrain.com",
  "mbx.cc",
  "mega.zik.dj",
  "meinspamschutz.de",
  "meltmail.com",
  "messagebeamer.de",
  "mezimages.net",
  "mfsa.ru",
  "mhwolf.net",
  "mierdamail.com",
  "migmail.net",
  "migmail.pl",
  "mijnhva.nl",
  "ministry-of-silly-walks.de",
  "mintemail.com",
  "misterpinball.de",
  "moncourrier.fr.nf",
  "monemail.fr.nf",
  "monmail.fr.nf",
  "monumentmail.com",
  "msa.minsmail.com",
  "mt2009.com",
  "mt2014.com",
  "mx0.wwwnew.eu",
  "mycleaninbox.net",
  "myemailboxy.com",
  "mymail-in.net",
  "mypacks.net",
  "mypartyclip.de",
  "myphantomemail.com",
  "myspaceinc.com",
  "myspaceinc.net",
  "myspaceinc.org",
  "myspamless.com",
  "mytempemail.com",
  "mytempmail.com",
  "mytrashmail.com",
  "neomailbox.com",
  "nepwk.com",
  "nervmich.net",
  "nervtmich.net",
  "netmails.com",
  "netmails.net",
  "neverbox.com",
  "nice-4u.com",
  "nincsmail.hu",
  "nmail.cf",
  "nnh.com",
  "no-spam.ws",
  "nobulk.com",
  "noclickemail.com",
  "nodezine.com",
  "nogmailspam.info",
  "nomail.pw",
  "nomail.xl.cx",
  "nomail2me.com",
  "nomorespamemails.com",
  "nospam.ze.tc",
  "nospam4.us",
  "nospamfor.us",
  "nospammail.net",
  "nospamthanks.info",
  "notmailinator.com",
  "notsharingmy.info",
  "nowhere.org",
  "nowmymail.com",
  "ntlhelp.net",
  "nullbox.info",
  "nuo.kr",
  "nurfuerspam.de",
  "nus.edu.sg",
  "nut.cc",
  "nuts2trade.com",
  "nwldx.com",
  "objectmail.com",
  "obobbo.com",
  "odaymail.com",
  "one-time.email",
  "oneoffemail.com",
  "onewaymail.com",
  "onlatedotcom.info",
  "online.ms",
  "oopi.org",
  "opayq.com",
  "ordinaryamerican.net",
  "otherinbox.com",
  "ourklips.com",
  "outlawspam.com",
  "ovpn.to",
  "owlpic.com",
  "pancakemail.com",
  "paplease.com",
  "pcusers.otherinbox.com",
  "pepbot.com",
  "pfui.ru",
  "pimpedupmyspace.com",
  "pjjkp.com",
  "plexolan.de",
  "poczta.onet.pl",
  "politikerclub.de",
  "poofy.org",
  "pookmail.com",
  "privacy.net",
  "privatdemail.net",
  "proxymail.eu",
  "prtnx.com",
  "prtz.eu",
  "psh.me",
  "punkass.com",
  "putthisinyourspamdatabase.com",
  "pwrby.com",
  "qasti.com",
  "qisdo.com",
  "qisoa.com",
  "qq.com",
  "quickinbox.com",
  "quickmail.nl",
  "rcpt.at",
  "reallymymail.com",
  "reallymymail.net",
  "recode.me",
  "recursor.net",
  "reliable-mail.com",
  "rhyta.com",
  "rmqkr.net",
  "royal.net",
  "rppkn.com",
  "rtrtr.com",
  "s0ny.net",
  "safe-mail.net",
  "safersignup.de",
  "safetymail.info",
  "safetypost.de",
  "sandelf.de",
  "saynotospams.com",
  "schafmail.de",
  "schmeissweg.tk",
  "schrott-email.de",
  "secretemail.de",
  "secure-mail.biz",
  "secure-mail.cc",
  "selfdestructingmail.com",
  "sendspamhere.com",
  "senseless-entertainment.com",
  "services391.com",
  "sex.163.com",
  "sharklasers.com",
  "shieldemail.com",
  "shiftmail.com",
  "shitmail.me",
  "shitmail.org",
  "shitware.nl",
  "shmeriously.com",
  "shortmail.net",
  "showslow.de",
  "sibmail.com",
  "sinnlos-mail.de",
  "siteposter.net",
  "skeefmail.com",
  "slapsfromlastnight.com",
  "slaskpost.se",
  "slipry.net",
  "slopsbox.com",
  "smashmail.de",
  "smellfear.com",
  "snakemail.com",
  "sneakemail.com",
  "sneakmail.de",
  "snkmail.com",
  "socialfurry.org",
  "sofimail.com",
  "sofort-mail.de",
  "sogetthis.com",
  "soodonims.com",
  "spam-protection.info",
  "spam.care",
  "spam4.me",
  "spamail.de",
  "spamarrest.com",
  "spambob.com",
  "spambob.net",
  "spambob.org",
  "spambog.com",
  "spambog.de",
  "spambog.net",
  "spambog.ru",
  "spambooger.com",
  "spambox.info",
  "spambox.irishspringrealty.com",
  "spambox.org",
  "spambox.us",
  "spamcannon.com",
  "spamcannon.net",
  "spamcero.com",
  "spamcon.org",
  "yopmail.com",
  "temp-mail.org",
];
