
version: "3.8"

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  app1:
    build: 
      context: .
      args:
        GITHUB_PAT: ${GITHUB_PAT}
    depends_on:
      - redis
    environment:
      - PORT=3001
      - SOCKET_ORIGINS=http://localhost:8080
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    expose:
      - "3001"

  app2:
    build:
      context: .
      args:
        GITHUB_PAT: ${GITHUB_PAT}
    depends_on:
      - redis
    environment:
      - PORT=3002
      - SOCKET_ORIGINS=http://localhost:8080
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    expose:
      - "3002"

  app3:
    build: 
      context: .
      args:
        GITHUB_PAT: ${GITHUB_PAT}
    depends_on:
      - redis
    environment:
      - PORT=3003
      - SOCKET_ORIGINS=http://localhost:8080
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    expose:
      - "3003"

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
      - app3
